server:
  error:
    include-stacktrace: always

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/srs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

